language: python
python: # Can test multiple versions of python
- "3.5"
- "3.6"

install:
- pip3 install django coverage coveralls # Install necessary packages

before_script:
- python3 manage.py migrate # Migrate database

script:
- coverage run --branch --source="./hero" manage.py test # Run test

after_success: coveralls # After test, report coverage to coveralls